module.exports = {
	channels: {
		MINIMIZE_WINDOW: 'minimize_window',
		MAXIMIZE_WINDOW: 'maximize_window',
		EXIT_APP: 'exit_app',
		FULLSCREEN_ENABLE:"fullscreen_enable",
		FULLSCREEN_DISABLE:"fullscreen_disable",
		FULLSCREEN_STATUS: "fullscreen_status",
		GET_FOLDER_WORLDSAVEROOT: "get_folder_worldsaveroot",
		GAMESETTINGS_GET_BY_KEY_AND_CATEGORY: "gamesettings_get_by_key_and_category",
		GAMESETTINGS_SET_BY_KEY_AND_CATEGORY: "gamesettings_set_by_key_and_category",
		FILEEXPLORER_OPEN_TO_PATH: "fileexplorer_open_to_path",
		FORCE_WRITE_SETTINGS: "force_write_settings",
		// SERVER_CONNECT: 'server_connect',
		WEBSOCKET_CONNECT_TO_SERVER: "websocket_connect_to_server",
		// SERVER_DISCONNECT: 'server_disconnect',
		WEBSOCKET_DISCONNECT_FROM_SERVER: "websocket_disconnect_from_server",
		// SERVER_HOST_START: "server_host_start",
		WEBSOCKET_START_SERVER: "websocket_start_server",
		// SERVER_HOST_STOP: "server_host_stop",
		WEBSOCKET_STOP_SERVER: "websocket_stop_server",
		WEBSOCKET_SEND_TO_CLIENTS: "websocket_send_to_clients",
		WEBSOCKET_SEND_TO_SERVER: "websocket_send_to_server",
		MDNS_START_SERVICE: "mdns_start_service",
		MDNS_STOP_SERVICE: "mdns_stop_service",
		// SERVER_FINDALL: "server_findall",
		MDNS_FIND_SERVICES: "mdns_find_services",
		DB_CONNECT: "db_connect",
		DB_DISCONNECT: "db_disconnect",
		DB_DOC_CREATE: "db_doc_create",
		DB_DOC_UPDATE: "db_doc_update",
		DB_DOC_DELETE: "db_doc_delete",
		DB_DOC_FIND_ONE: "db_doc_find_one",
		DB_DOC_FIND_MANY: "db_doc_find_many",
		DB_DOC_FIND_ALL: "db_doc_find_all",
		DB_USER_REGISTER: "db_user_register",
		DB_USER_VERIFY_PASSWORD:"db_user_verify_password",
		DB_USER_UPDATE_PASSWORD:"db_user_update_password"

	}
}