name: Deploy

on: 
  push:
    branches: [main]


jobs:
  build-website:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
        
      - name: Set up NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: lts/*
      
      - name: Install dependencies
        run: |
          npm install

      - name: Build the site
        run: |
          npm run build
      
      - name: Deploy
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: gh-pages
          FOLDER: build
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}